/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge05;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        LinkedList list1 = new LinkedList();
        LinkedList list2 = new LinkedList();
        LinkedList listAnswer = new LinkedList();
        int value;

        // To insert three number to linked list
        for (int i = 0; i < 3; i++) {
            System.out.println("Is the linked list1 empty => "+list1.isEmpty());

            System.out.println("Please enter a number to add to linked list1");
            value = input.nextInt();
            //list.insertFirst(value);
            // or insert last method
            list1.insertLast(value);
        }
        for (int i = 0; i < 3; i++) {
            System.out.println("Is the linked list2 empty => "+list2.isEmpty());

            System.out.println("Please enter a number to add to linked list2");
            value = input.nextInt();
            //list.insertFirst(value);
            // or insert last method
            list2.insertLast(value);
        }

        //this four lines to check If number existing or not(include method)
//        System.out.println("Please enter a number to check if added to linked list");
//        int value2 = input.nextInt();
//        String s = list.includes(value2)? "The number added":"The number is not found";
//        System.out.println(s);

        //this four line to add number before any existing number(add before method)
//        System.out.println("To use insert before features please enter the new number then the number you want to insert before");
//        int value3 = input.nextInt();
//        int value4 = input.nextInt();
//        list.insertBefore(value3,value4);

        //this four line to add number after any existing number(add after method)
//        System.out.println("To use insert after features please enter the new number then the number you want to insert after");
//        int value6 = input.nextInt();
//        int value5 = input.nextInt();
//        list.insertAfter(value6,value5);

        // this line to print out whole linked list
        System.out.println("Your linked list1 is => "+list1.to_string());
        System.out.println("Your linked list1 is => "+list2.to_string());
//
//
////        System.out.println("enter the index for element you want to get its value");
////        int k = input.nextInt();
////        System.out.println(list.kthFromEnd(k));
        String answer = listAnswer.zipLists(list1,list2);
        System.out.println(answer);
        input.close();

    }
}
